### ISSUE TITLE
The game resets after pressing a back button

### ISSUE THREAD

**Issue by jkozh** [ericmaxwell2003/ticTacToe#1]

**Comment by ericmaxwell2003** [comment]
Hi Julia,  

Thanks for giving me feedback.  

That is true, there is no state saving in this example.  So if you leave the activity and come back, the game is reset.  I guess I could save state by overriding onSaveInstanceState and using it to store/restore state.  Or introduce persistence in the model itself. 

My goal in this example was just to illustrate the concepts of my post.  If you would like to create a PR to add this functionality, that would be awesome!  :-) 

Eric
