### ISSUE TITLE
Stop using android:screenOrientation="portrait"

### ISSUE THREAD

**Issue by amilcar-andrade** [ericmaxwell2003/ticTacToe#10]
Most of the applications support landscape and portrait orientations. I think your demo should support those fully. 

Right now the activity does not get destroyed and it is really easy to see the benefits of MVP and MVVM because the presenters or view models are not being destroyed.

**Comment by ericmaxwell2003** [comment]
Hi @amilcar-andrade , thank you for the comment.  I tried to make this demo as simple as possible to illustrate the concepts referenced in my post.  There are several things that I would do additionally if I were planning to release this application, allowing landscape orientations being one of them.  I considered adding support for this initially, but didn't feel that this added value to the post.

> Right now the activity does not get destroyed and it is really easy to see the benefits of MVP and MVVM because the presenters or view models are not being destroyed.

Can you clarify your concern?  Do you think one approach MVC,MVVM, MVP looks more or less attractive when handling rotation in the activity lifecycle.

**Comment by amilcar-andrade** [comment]
All of them are good patterns, I guess it is a little bit easier to just use MVC because as you know Android uses MVC so you can easily save the data in the controller using the `onSaveInstace` or the `onRetainCustomNonConfigurationInstance` and get back the date inside the `onCreaste` method. Handling orientation changes is a little bit easier if you treat your `Activity` or `Fragment` as the controller.

In your MVP example, you are just instantiating once the presenter and assuming that the presenter is always going to be there with the available data and the view. If you support different orientations then you will need to add the appropriate methods to the interface to detach and attach the view also you will need to implement a proper data manager or data loader class or use a Loader inside the presenter so you can fetch your data once from a server or database and then just return the cached data for subsequent requests.

Just to be clear I am not saying your project is wrong or it is not showing the correct implementation of MVC, MVP and MVVM. I am just pointing out that is a naive implementation (no offence)

**Comment by ericmaxwell2003** [comment]
Sure I understand, that's a valid point! ... and no offense taken, I just needed clarification :-) 

I agree it is a very simple example and would be nice to see a bigger example with multiple activities and fragments to see how each pattern scales with greater complexity.  Although, sometimes I feel it's easy to get lost in the detail though when you're looking at a large project and trying to grasp a new concept.  I did try to steer developers to the [Android Architecture Blueprints](https://github.com/googlesamples/android-architecture) for more complex examples of MVP and MVVM in the post that goes along with this project.
