### ISSUE TITLE
MVP branch, interface Presenter

### ISSUE THREAD

**Issue by wsw22** [ericmaxwell2003/ticTacToe#5]
This is my understanding, "In MVP, C is divided into two parts, one is added into V, so view can be mo intelligent, the other become P which handle the logic". If I misunderstand, please correct me.

What make me confused is the Presenter interface is so simple, 
`public interface Presenter {
    void onCreate();
    void onPause();
    void onResume();
    void onDestroy();
}`

and in TicTacToeActivity 
`    TicTacToePresenter presenter = new TicTacToePresenter(this);`
`                presenter.onResetSelected();`
`        presenter.onButtonSelected(row, col);`
the activity can see the presenter, why the two methods are not decaled in the interface?

**Comment by gugakatsi** [comment]
this is presenter interface which every other presenter like TicTacToe presenter should implement,  you should look in TicTacToePresenter instead.
